### ISSUE TITLE
不太行

### ISSUE THREAD

**Issue by mlnwa** [freefq/tutorials#11]
试了好几个节点都没成功

**Comment by freefq** [comment]
这个教程为了简单，省略了测速步骤，可以先批量选多几个节点，右键测真链接延迟测速，等结果出来找延迟小的节点用

如何快速的选择有效节点？
批量选中导入节点（可以Ctrl+a），右键菜单中选择测试服务器真连接延迟（快捷键是Ctrl+r），从测试结果中选择延迟最低的节点设为活动服务器（Enter）。

**Comment by mlnwa** [comment]
有可以用的 速度还挺快 针不戳
